export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // Courses
  COURSES_VIEW: "COURSES_VIEW",
  COURSES_CREATE: "COURSES_CREATE",
  COURSES_UPDATE: "COURSES_UPDATE",
  COURSES_DELETE: "COURSES_DELETE",

  // Lessons
  LESSONS_VIEW: "LESSONS_VIEW",
  LESSONS_CREATE: "LESSONS_CREATE",
  LESSONS_UPDATE: "LESSONS_UPDATE",
  LESSONS_DELETE: "LESSONS_DELETE",

  // Enrollments
  ENROLLMENTS_VIEW: "ENROLLMENTS_VIEW",
  ENROLLMENTS_CREATE: "ENROLLMENTS_CREATE",
  ENROLLMENTS_UPDATE: "ENROLLMENTS_UPDATE",
  ENROLLMENTS_DELETE: "ENROLLMENTS_DELETE",

  // Field-level visibility
  ENROLLMENT_INFO_EMAIL_VIEW: "ENROLLMENT_INFO_EMAIL_VIEW",

  // Topics
  TOPICS_VIEW: "TOPICS_VIEW",
  TOPICS_CREATE: "TOPICS_CREATE",
  TOPICS_UPDATE: "TOPICS_UPDATE",
  TOPICS_DELETE: "TOPICS_DELETE",

  // Documents
  DOCUMENTS_VIEW: "DOCUMENTS_VIEW",
  DOCUMENTS_CREATE: "DOCUMENTS_CREATE",
  DOCUMENTS_UPDATE: "DOCUMENTS_UPDATE",
  DOCUMENTS_DELETE: "DOCUMENTS_DELETE",

  // Notes
  NOTES_VIEW: "NOTES_VIEW",
  NOTES_CREATE: "NOTES_CREATE",
  NOTES_UPDATE: "NOTES_UPDATE",
  NOTES_DELETE: "NOTES_DELETE",

  // Teams
  TEAMS_VIEW: "TEAMS_VIEW",
  TEAMS_CREATE: "TEAMS_CREATE",
  TEAMS_UPDATE: "TEAMS_UPDATE",
  TEAMS_DELETE: "TEAMS_DELETE",

  // Schedule (study blocks)
  SCHEDULE_VIEW: "SCHEDULE_VIEW",
  SCHEDULE_CREATE: "SCHEDULE_CREATE",
  SCHEDULE_UPDATE: "SCHEDULE_UPDATE",
  SCHEDULE_DELETE: "SCHEDULE_DELETE",

  // Analytics
  ANALYTICS_VIEW: "ANALYTICS_VIEW",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Backend sends lowercase codes (e.g. `courses_view`); the app compares uppercase. */
export function normalizePermissions(codes: string[] = []) {
  return codes.map((code) => code.toUpperCase());
}
